# Generated by Django 3.1.3 on 2020-11-09 09:25

import bart_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=bart_gallery.models.upload)),
                ('path', models.CharField(default='defaul_path', max_length=255)),
                ('fullpath', models.CharField(default='defaul_fullpath', max_length=255)),
                ('name', models.CharField(blank=True, default='defaul_fullpath', max_length=255, null=True)),
                ('modified', models.DateTimeField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('images', models.ManyToManyField(null=True, to='bart_gallery.Image')),
            ],
        ),
    ]
